export const TEXTS = {
    common: {
        save: "Enregistrer",
        cancel: "Annuler",
        delete: "Supprimer",
        duplicate: "Dupliquer",
        confirm: "Confirmer",
        close: "Fermer",
        loading: "Chargement...",
    },
    auth: {
        login: "Se connecter",
        register: "Créer un compte",
        email: "Email",
        password: "Mot de passe",
        name: "Prénom",
        newHere: "Nouveau ici ?",
        loginTagline: "Organisez votre vie de famille ensemble",
    },
    calendar: {
        title: "Planning",
        addEvent: "Nouvel événement",
        today: "Aujourd'hui",
        noEvents: "Rien de prévu ce jour-là.",
    },
    dashboard: {
        greeting: "Bonjour",
        nextEvent: "Prochain événement",
        upNext: "À suivre",
        tasks: "Tâches",
        noTasks: "Aucune tâche pour le moment",
        members: "Membres",
        noMembers: "Aucun membre trouvé",
        createEvent: "Créer un nouvel événement",
        createTask: "Créer une nouvelle tâche",
    },
    navigation: {
        home: "Accueil",
        calendar: "Calendrier",
        tasks: "Tâches",
        settings: "Paramètres",
    },
    event: {
        title: "Titre",
        date: "Date",
        category: "Catégorie",
        create: "Créer l'événement",
        createSuccess: "Événement créé avec succès !",
        updateSuccess: "Événement modifié avec succès !",
        deleteSeries: "Supprimer toute la série",
        deleteSingle: "Supprimer uniquement cet événement",
        updateSeries: "Modifier toute la série",
        updateSingle: "Modifier cet événement",
        seriesWarning: "Cet événement fait partie d'une série.",
        seriesUpdateWarning: "Cet événement fait partie d'une série. Voulez-vous modifier uniquement cet événement ou toute la série ?",
        time: "Heure",
        startTime: "Début",
        endTime: "Fin",
        details: "Détails",
        edit: "Modifier",
    },
    errors: {
        generic: "Une erreur est survenue",
        unauthorized: "Vous devez être connecté",
        notFound: "Introuvable",
        missingFields: "Veuillez remplir tous les champs",
    }
} as const
